name: run full test

on:

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install -r tests/misc/requirements.txt
      - name: Install test dependencies
        run: |
          pip install -e ./
          pip install -r tests/misc/requirements.txt
      - name: Run smoke test
        run: python pytest
        working-directory: example
        env:
          API_BASE_PATH: "https://faceapi.regulaforensics.com/"
